Repository estarossa0/webserv, pull requests merged in 2021-07, with the labels that each got.

#56 ServerData parsing mode is now accessible only from ConfigParser class
  includes/ServerData.hpp
  srcs/ConfigParser.cpp
  srcs/ServerData.cpp
Labels: enhancement

#72 style: removed some newlines & spaces
  includes/Location.hpp
  includes/Request.hpp
  includes/Response.hpp
  includes/ServerData.hpp
  srcs/Location.cpp
  srcs/Request.cpp
  srcs/Response.cpp
Labels: enhancement

#76 pr to master
  srcs/Webserv.cpp
Labels: bug

#82 fix(parser): fix wrong usage of webserv executable arguments
  includes/ConfigParser.hpp
  srcs/ConfigParser.cpp
  srcs/main.cpp
Labels: bug

#83 refactor: put logs in constructor and destructor
  includes/Webserv.hpp
  srcs/Webserv.cpp
  srcs/main.cpp
Labels: enhancement

#88 fix(response): directory now returns 404 if no index was found
  srcs/Response.cpp
Labels: bug

#89 fix(cgi): php coookie management
  public/cgi/home.php
  public/cgi/login.php
  public/cgi/logout.php
  srcs/cgi.cpp
Labels: bug

#91 fix(parser): fix the last additional check
  srcs/ConfigParser.cpp
Labels: bug

#92 PR to master from dev
  includes/ConfigParser.hpp
  includes/Request.hpp
  includes/Webserv.hpp
  public/cgi/home.php
  public/cgi/login.php
  public/cgi/logout.php
  public/cgi/upload.php
  srcs/ConfigParser.cpp
  srcs/Request.cpp
  srcs/Response.cpp
  srcs/Webserv.cpp
  srcs/cgi.cpp
  srcs/main.cpp
Labels: bug, enhancement
