Repository estarossa0/webserv, pull requests merged in 2021-06, with the labels that each got.

#7 parse multiple server names and remove getPortsServerDataMap() method
  includes/ConfigParser.hpp
  includes/ServerData.hpp
  srcs/ConfigParser.cpp
  srcs/ServerData.cpp
  srcs/main.cpp
Labels: enhancement

#10 easy access map
  includes/Server.hpp
  srcs/Server.cpp
Labels: enhancement

#14 fix(parser): fix assignation operator return type qualifier
  includes/Location.hpp
  includes/ServerData.hpp
  srcs/Location.cpp
  srcs/ServerData.cpp
Labels: bug

#20 feat(logs): add logs file for the webserv logs
  includes/Webserv.hpp
  srcs/ConfigParser.cpp
  srcs/Webserv.cpp
  srcs/main.cpp
Labels: enhancement

#21 fix cgi error and add missing cgi variables
  includes/Response.hpp
  srcs/Response.cpp
  srcs/cgi.cpp
Labels: bug

#22 fix(parser): make default value of upload_enable false
  srcs/Location.cpp
Labels: invalid

#24 refact(parser): show the missing elements in a server config
  includes/ConfigParser.hpp
  includes/ServerData.hpp
  srcs/ConfigParser.cpp
  srcs/ServerData.cpp
Labels: enhancement

#23 feat: request and response update
  includes/Request.hpp
  includes/Response.hpp
  srcs/Connection.cpp
  srcs/Request.cpp
  srcs/Response.cpp
Labels: enhancement

#26 add server log and fix cgi missing headers
  srcs/Server.cpp
  srcs/Webserv.cpp
  srcs/cgi.cpp
Labels: bug, enhancement

#38 fix some errors messages and skip logs when opening logs file fails
  Makefile
  includes/ConfigParser.hpp
  srcs/ConfigParser.cpp
  srcs/Webserv.cpp
  srcs/outputLogs.cpp
Labels: bug

#42 fix(server): fix server indexing, closes #41
  srcs/Webserv.cpp
Labels: bug

#50 fix: adding index equal connections size as outOfRange
  srcs/Webserv.cpp
Labels: bug
